# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

homepage:
  greetings: Welcome to Yanghao's Homepage!
  intro: I am an applied economist with research interests in industrial organization, consumer economics, and development economics. I am enthused about learning newly developed econometric and machine learning models and adapting proper methods to solve real-world economic problems.
  background: I currently work in the Global Data Insight and Analytics at Ford Motor Company. I hold a Ph.D. degree in Applied Economics from the University of Minnesota and a M.S. degree in Agricultural Economics with Minor in Statistics from the University of Tennessee.

# 网站图标
favicon:
  enable: true
  icon: /images/isle_icon.png
  touch_icon: /images/isle_icon.png

# 用户头像与昵称
avatar:
  author_photo: /images/isle_icon.png
  author_nickname: Yanghao Wang
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: true
  gtagkey: G-HQF7RSRVHX

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，zxcxxxx即为shortname
    enable: true
    shortname: https-yanghaowang-github-io

# 主题页面导航栏
navbar:
  -
    name: Home
    enable: true
    path: /
    key: home
  -
    name: Research
    enable: true
    path: /research/
    key: research
  -
    name: Archives
    enable: false
    path: /archives/
    key: archives
  -
    name: Categories
    enable: false
    path: /categories/
    key: categories
  -
    name: Tags
    enable: true
    path: /tags/
    key: tags
  -
    name: Friends
    enable: false
    path: /friends/
    key: friends
  -
    name: About
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    # -
    #   name: github
    #   icon: github
    #   path: https://github.com/yanghaowang # https://github.com/zchengsite/hexo-theme-oranges
    -
      name: linkedin
      icon: linkedin
      path: https://www.linkedin.com/in/yanghaowang
    -
      name: email
      icon: envelope
      path: mailto:wyangh90@gamil.com
    # -
    #   name: facebook
    #   icon: facebooksquare
    #   path:
    # -
    #   name: twitter
    #   icon: twitter
    #   path:
    # -
    #   name: wechat
    #   icon: wechat
    #   path:
    # -
    #   name: weibo
    #   icon: weibo
    #   path:
    -
      # rss需安装 hexo-generator-feed 插件
      # 具体参照https://github.com/hexojs/hexo-generator-feed
      name: rss
      icon: rss
      path: /atom.xml

  more:
    -
      name: © 2018-2020 Yanghao Wang. All Rights Reserved.
      # path: / # https://yanghaowang.github.io/
    # -
    #   name: Hosted on GitHub | Powered by Hexo | Theme by Oranges
    #   path: / # https://github.com/zchengsite/hexo-theme-oranges

# 文章搜索
search:
  enable: false
  placeholder: 
